#!/usr/bin/bash
lic=$(cat licence)
#curl -X 'GET'   'https://yfapi.net/v8/finance/spark?interval=1d&range=max&symbols=0P00015E7M.l,0P000023C7.L,0P000023CJ.L,0P000023NV.L,0P00002059.L,0P000023C5.L,0P000023HM.L,0P000102ML.L,0P0000HN9B.L'   -H 'accept: application/json'   -H 'X-API-KEY: '$lic
curl -X 'GET'   'https://yfapi.net/v8/finance/spark?interval=1d&range=max&symbols=0P00015E7M.l,0P000023C7.L,0P000023CJ.L,0P000023NV.L,0P000023C5.L,0P000023HM.L,0P000102ML.L,0P0000HN9B.L,ISF.L,0P0000X7CG.L'   -H 'accept: application/json'   -H 'X-API-KEY: '$lic