#!/usr/bin/bash
lic=$(cat licence)
stocks=$(cat stocks)
curl -X 'GET'   'https://yfapi.net/v8/finance/spark?interval=1d&range=max&symbols='$stocks   -H 'accept: application/json'   -H 'X-API-KEY: '$lic