#!/usr/bin/bash
fund=${1:-0p000102ml.l}
date=$(date +%s)
curl -X 'GET' \
  "https://yfapi.net/v7/finance/options/$fund?date=$date" \
  -H 'accept: application/json' \
  -H 'X-API-KEY: dl6c4tTQh9419GRm0JIsT3spcRXDGfz03miP7ju5'
