#!/bin/bash
lic=$(cat licence)
fund=${1:-0P0000X7CH.L}
date=$(date +%s)
curl -X 'GET' \
  "https://yfapi.net/v7/finance/options/$fund?date=$date" \
  -H 'accept: application/json' \
  -H 'X-API-KEY: '$lic
