#!/usr/bin/bash
fund=${1:-0p000102ml.l}
date=$(date +%s)
curl -X 'GET' \
  "https://yfapi.net/v7/finance/options/$fund?date=$date" \
  -H 'accept: application/json' \
  -H 'X-API-KEY: 46wsx8yvbS7HGM8sPIchJ81M6TbBVXZx78qb7M1C'
